### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by hasalex** [davidmarkclements/bespoke-pdf#4]
When I try to install bespoke-pdf  (npm install bespoke-pdf), I have the following error:

```
/home/sewatech/my-bespoke-demo/node_modules/install-nw/cmd.js:121
  version = [v.major, v.minor, v.patch].join('.');
              ^

TypeError: Cannot read property 'major' of null
    at down (/home/sewatech/my-bespoke-demo/node_modules/install-nw/cmd.js:121:15)
    at init (/home/sewatech/my-bespoke-demo/node_modules/install-nw/cmd.js:72:11)
    at Object.<anonymous> (/home/sewatech/my-bespoke-demo/node_modules/install-nw/cmd.js:41:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
```
My environment is

- Ubuntu 16.04 or MacOS 10.11 (same error on both systems)
- NodeJS v7.1.0
- npm 3.10.9

**Comment by davidmarkclements** [comment]
Electron may have changed their versioning pattern again
